# Generated by Django 4.2.7 on 2025-04-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AQ_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurements",
            name="value",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
